### ISSUE TITLE
Potential /features endpoint

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#156] opened 2020-09-20 17:29 UTC
I have a note that the idea of having a /features endpoint came up in conversation
The /features endpoint might specify if the server supports such things as:
- asynchronous
- callback
- supported_query_graph_types
- max_hops
etc.

**Comment by vdancik** [comment] 2020-09-24 15:57
This is similar to / duplicate of #142

**Comment by vgardner-renci** [comment] 2021-07-15 17:06
Ready to close

**Closed by vgardner-renci** 2021-07-15 17:06 UTC
