### ISSUE TITLE
Support for multiple identifiers

### ISSUE THREAD

**Issue by vdancik** [NCATSTranslator/ReasonerAPI#145] opened 2020-08-20 17:12 UTC
There are three situations where we may want to support multiple identifiers (right now every entity has a single identifier):

1. Equivalent identifiers for the same entity - to help PKs with unnecessary node normalization.
2. A set of entities (addressed by #117) - e.g. a set of genes related when asking to a pathway they related.
3. Batch query - repeat the same query for multiple ids.

**Comment by patrickkwang** [comment] 2020-09-16 16:31
> ARAs or other integration tools such as KGX will perform node identifier equivalence translations.
> 
> The consortium will produce or adopt equivalent id sets, which will be shared across Translator tools. Multiple Translator teams will contribute expertise to these sets, but that expertise will produce centralized results.
>
> SRI will provide tools for disseminating these equivalent identifiers, drawing on the prior work of multiple Translator teams.

 -- **[Translator Architecture](https://github.com/NCATSTranslator/TranslatorArchitecture/blob/5a9266f52b9081b4eada92e273f9d743f3de4924/README.md#architecture-principles)**

This implies to me that servers should not return lists of equivalent identifiers, and clients can just consult shared normalization services as necessary.

**Comment by patrickkwang** [comment] 2020-09-16 18:14
Your item 3 is a duplicate of #124.

**Comment by edeutsch** [comment] 2021-04-29 07:10
Implemented in TRAPI 1.1

**Closed by edeutsch** 2021-04-29 07:10 UTC
